// Generated by lsc from index.ts

function isSupportedLocaleCode(value: string): bool
{
  (((value == "zh-TW") || (value == "en")) || (value == "ja"))
}

lemma isSupportedLocaleCode_ensures(value: string)
  ensures (isSupportedLocaleCode(value) == (((value == "zh-TW") || (value == "en")) || (value == "ja")))
{
}
