// Generated by lsc from routes.ts

datatype Option<T> = None | Some(value: T)

function resolveRouteStatus(metaStatus: Option<int>): int
{
  match metaStatus {
    case Some(i_metaStatus_val) =>
      i_metaStatus_val
    case None =>
      200
  }
}

lemma resolveRouteStatus_ensures(metaStatus: Option<int>)
  ensures ((resolveRouteStatus(metaStatus) == 200) || (match metaStatus { case Some(i_value) => (i_value == resolveRouteStatus(metaStatus)) case None => false }))
{
}
